### ISSUE TITLE
DCF Integration into Portal 

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1007]
The DCF (Data Commons Framework - https://nci-crdc.datacommons.io) hosts the TARGET files, which the KFDRP will integrate with. Authentication/authorization to DCF files will be done through a separate instance of a Gen3/Fence deployment. The TARGET study will be loaded into the dataservice (SD_YNSSAPHE).

For these files we need to:
> - Allow users to authenticate to a separate Gen3/Fence instance in the integrations
> - Have the "Allowed studies" dashboard read and present info rom all authenticated sources
> - Have the file download on each file entity page/download row on repository reference the correct download domain with the right token

In future, there will be other integrations as well.  We need to extend the integration functionality to accept a general solution. 

- [ ] Repository Field needed in model
https://github.com/kids-first/kf-portal-etl/issues/63
- [ ] Extend the Fence KeyManager to new DCF Fence
https://github.com/kids-first/kf-key-management/issues/19
- [ ] Generalize File Download 
#1026
- [ ] Front-end Implementation for integration
https://github.com/kids-first/kf-portal-ui/issues/1027
