### ISSUE TITLE
Portal Notifications 

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1136]
### FOLLOW BUTTON on entity pages (with the action area):
Zeplin: https://zpl.io/bAZwggB
- [ ] When users are able to "follow" entities (including other members and virtual studies that are marked in settings as public), a follow button will be implemented (with the page actions) on entity/virtual study pages.  
![screen shot 2019-01-29 at 4 27 47 pm](https://user-images.githubusercontent.com/18424138/51941559-edc1e880-23e2-11e9-81a2-758eedd0c34a.png)

- [ ] When users clicks on it, the entity becomes something they follow. The button changes: 
![screen shot 2019-01-29 at 4 27 52 pm](https://user-images.githubusercontent.com/18424138/51941569-f4e8f680-23e2-11e9-8a97-44f2d13e9203.png)

- [ ] They can click on this button again to unfollow that entity. The hover state changes to: 
<img width="134" alt="screen shot 2019-01-30 at 10 31 37 am" src="https://user-images.githubusercontent.com/18424138/51992029-4abcad80-247a-11e9-8bf5-aaa101df3f40.png">

### DASHBOARD NOTIFICATIONS: https://zpl.io/b6j5z8W
- [ ] Users receive notifications on their dashboard with activity about these entities they follow
![screen shot 2019-01-28 at 4 35 45 pm](https://user-images.githubusercontent.com/18424138/51867958-cb649800-231a-11e9-8c6b-3f5dc3aeae82.png)

- [ ] Dashboard cards can use the tabbed navigation to separate owned entities vs ones a user is following. For example, if the user can follow Virtual Studies - by default the card lands on the studies they own and are collaborating on. They can also access the ones they are following:
![screen shot 2019-01-28 at 4 35 48 pm](https://user-images.githubusercontent.com/18424138/51868038-036bdb00-231b-11e9-81f1-4f993adbf909.png)

### USER PROFILE
- [ ] Users can manage their following within their user profile
Example1: Simon's logged in and views his own profile: https://zpl.io/bldoKgk 
Example2: Simon is logged in and views Claire's profile: He isn't folllowing her yet but she has her profile set as public so he can see who she is following: https://zpl.io/bAZwggB

### PRIVACY SETTINGS
Privacy may need to be revisited and extended on from this version: https://github.com/kids-first/kf-portal-ui/issues/1137
