### ISSUE TITLE
Quick Search or Global Search on Portal

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#1137]
As a user, I want to be able to do a free-text search that searches through all data types on the portal.

## Acceptance criterias
- Results must be sorted (see the relevant sub-task issue)

## Mockups

**Search Box**
- [ ] Search box with dropdown:
Zeplin: https://zpl.io/bPXBdRL
- [ ] To-do: sort order for results: https://github.com/kids-first/kf-portal-ui/issues/1249
![screen shot 2019-03-05 at 10 24 10 am](https://user-images.githubusercontent.com/18424138/53816047-dcfc1980-3f30-11e9-883a-c39599c3a0fe.png)

**Search Results Page**
- [ ] Note; the left sidebar for "refine your search" moves down the page as the user scrolls so they always have access to it.
- [x] To-do: reviewing + confirming the teaser content for each entity type
- [ ] To-do: sort order for results: https://github.com/kids-first/kf-portal-ui/issues/1249
Zeplin: https://zpl.io/adrKMD5
![01 kidsfirst-general-search-results-notes](https://user-images.githubusercontent.com/18424138/53815869-868edb00-3f30-11e9-9676-26ddc7436f0a.jpg)

## See also
- Privacy: https://github.com/kids-first/kf-portal-ui/issues/1247
