### ISSUE TITLE
Release 2.5.0

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1933]
Item to track the tasks for the release 2.5.0

## Tasks
- [x] Update release notes
- [x] Update version number
- [x] Update the env vars (for the data release version number)
- [ ] Merge into master.

## Details
- No need to deploy persona
- No need to deploy riff
