### ISSUE TITLE
Change the `participant.phenotype` field to a nested type

### ISSUE THREAD

**Issue by jberube** [kids-first/kf-portal-ui#1956]
## Goal

We need to update the type of the following fields in graphql from `object` to `nested` to support and array of values instead of a single one:

- `participant.phenotype`
- `participant.files.family.family_compositions.family_members`
- `file.participants.phenotype`
- `file.participants.family.family_compositions.family_members`

See: https://github.com/kids-first/kf-es-model/pull/48

### Preparation

- [x] Merge the fix from https://github.com/overture-stack/arranger/pull/523 into `kids-first/arranger`'s `admin-ui` https://github.com/kids-first/arranger
- [x] Publish the updated version of `kids-first/arranger`'s `admin-ui` to npm (minor)
- [x] Update the version of the dependency of `kids-first/kf-arranger` to include the fix
- [ ] Deploy the `admin-ui` into QA

### Action

- [x] Publish the ETL in QA
- ⚠️ From this point forward, there is a risk that QA will be unstable or broken
- [x] Make the change to the 4 `phenotype` fields to match the ES model using the upgraded `admin-ui`
- [x] Change the environment variable (locally or in QA) in `kf-portal-ui` to point to the new index's projectid (`REACT_APP_PROJECT_ID`)
- ⚠️ From this point forward, there is a chance that QA will be stable again, but no guarantee. If not, proceed with _More actions_

### More actions

- [ ] See what breaks in `portal-ui` and fix it asap!

**Comment by aalex** [comment]
(QA) It seems like searches with Phenotypes yield no more results in QA.

![image](https://user-images.githubusercontent.com/293677/61816399-45815f80-ae1a-11e9-83a6-bcd6c0c824c2.png)

![image](https://user-images.githubusercontent.com/293677/61816369-3a2e3400-ae1a-11e9-932c-2797b4cef90c.png)
