### ISSUE TITLE
Operations for release 2.7.0 (studies renaming, families, phenotypes...)

### ISSUE THREAD

**Issue by aalex** [kids-first/kf-portal-ui#1959]
As developers and release coordinators, we need to follow a sequence of operations in order to do the release in which we will rename the studies.

# Release v2.7.0

- Bump kf-portal-ui version to 2.7.0

## Renaming the studies

See https://github.com/kids-first/kf-portal-ui/issues/1851 for some technical details.

Follow the sequence of operation detailed below.

- [ ] Rename the studies in the release coordinator
- [ ] Run the ETL (rename the studies) without publishing
- [ ] Upgrade riff in prod (rename studies)
- [ ] Publish the ETL
- [ ] Update Riff
- [ ] Update the environment variables or Netlify

## Families and phenotype

⚠️  TODO

**Comment by aalex** [comment]
There are still fixes/changes to be be done before we can confirm that we can proceed - likely on Thursday.

**Comment by nyanofthemoon** [comment]
**RoadMap**

QA
- Publish and Deploy NPM arranger/components

PROD
- ElasticSearch new Project ID
- Roule ETL
- Maintenance ON UI
- Deploy ETL
- Deploy UI using ElasticSearch new Project ID
- Deploy RIFF
- Maintenance OFF UI
