### ISSUE TITLE
Cluster shutdown pop-up

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2561]
### Feature
After a certain period of inactivity, we need to shut down the cluster automatically. So, after 1 hour of inactivity on the cluster, we will display a popup asking the users to confirm if they are still active by clicking on a button. This popup will have a 5min timer at the end of which the cluster will shutdown if the user does not confirm he is still there.

### Acceptance Criteria

**Scenario 1**
1. The user opens a cluster
2. The user lets the cluster inactive (no activity) for an hour
3. A pop-up appears warning the user that the cluster will shut down in 5 minutes
4. The user clicks "Shut down" and the cluster shuts down

**Scenario 2**
1. The user opens a cluster
2. The user lets the cluster inactive (no activity) for an hour
3. A pop-up appears warning the user that the cluster will shut down in 5 minutes
4. The user does nothing and the pop-up and the cluster shut down after the 5 minutes has passed

### Sub-Tasks
- [ ] Pop-up Mockup (Denis)
- [ ] Pop-up Design (Lucas)
- [ ] Front-end development
- [ ] Back-end development

### Testing Strategy
**Who can test it?**
Anybody with access to launch cluster and use notebooks

**How do we test it?** 
See described scenarios above

### Resources
**Pop-up text**
There hasn't been any activity on your cluster for the past hour. Your cluster will automatically be shut down in the next five minutes, or you can keep it running.

**Comment by evans-g-crsj** [comment]
Note: transfer repo into kf
