### ISSUE TITLE
Deleting a saved set

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2603]
### Feature

Users need to be able to delete their saved sets if they want to.

### Acceptance Criteria

**Scenario 1** 
  - **Given:** the user is on the Dashboard
    - **And:** the user has at least one saved set already
  - **When:** the user clicks on the trash icon
  - **Then:** a confirmation window is displayed asking the user to confirm the deletion
  - **When:** the user clicks on the Cancel button
  - **Then:** the confirmation window disappears and the set has not been deleted

**Scenario 2** User has multiple saved sets
  - **Given:** the user is on the Dashboard
    - **And:** the user has more than one saved set already
  - **When:** the user clicks on the trash icon
  - **Then:** a confirmation window is displayed asking the user to confirm the deletion
  - **When:** the user clicks on the Confirm button
  - **Then:** the confirmation window disappears and the set has been deleted. The saved set does not appear in the list anymore

**Scenario 3** User has only one saved set
  - **Given:** the user is on the Dashboard
  - **When:** the user clicks on the trash icon
  - **Then:** a confirmation window is displayed asking the user to confirm the deletion
  - **When:** the user clicks on the Confirm button
  - **Then:** the confirmation window disappears and the set has been deleted. The saved set does not appear in the list anymore
    - **And:** we can see the message "No saved sets" displayed in the Saved sets card on the Dashboard

### Sub-Tasks
_List of what needs to be done  on the technical side._
- [ ] Prepare Saved Set for deletion in Arranger
- [ ] Manage Saved Set deletion on the Lambda's side

### Testing Strategy
Anyone with access to the bastion and the portal in QA can test.
- [ ] Test the scenarios above
- [ ]  We also need to make sure that the sets are not queryable from the users notebooks anymore if the user is a X01.

_(!!) What happens if the user had a notebook including queries using the deleted set ? Do we need any validations/warning messages ?_

_(!!) What happens if the user had virtual studies using the deleted set. Do we update references automatically for the user or do we show any kind of validations/warning messages ?_

### Defects
_List of defects/bugs found during QA._
- [ ] Defect ...

### Resources

_Include any links to additional documentation, technical and/or design specs_

**Comment by denis-crsj** [comment]
Tested the deletion of the set and it works! We just need someone to test and see if the set is still available from the notebooks or not.
