### ISSUE TITLE
Using a set in the Cohort Builder

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2668]
### Feature

We want users to be able to use their Saved sets in their queries in the Cohort Builder.

### Acceptance Criteria

**Scenario 1** (User has no Saved set)
  - **Given:** The user is on the Cohort Builder
  - **Then:** The "My Sets" filter is greyed out and unclickable

**Scenario 2** (User has at least 1 Saved set)
  - **Given:** The user is on the Cohort Builder
  - **When:** The user clicks on the "My sets" filter, a modal open and lets the him choose which set he wants to add to his query
    - **And:** Once the user selects a set and clicks Submit
  - **Then:** The following term is added to the query "Participants ID in [name of Saved set]"

### Sub-Tasks
_List of what needs to be done  on the technical side._
- [ ] Sub-task ...

### Testing Strategy
_What do we need to test? Who can test it? How do we test it? What do we need to test it?_

### Defects
_List of defects/bugs found during QA._
- [x] "Add To Query" button should be written "Add to query" with no capital letters except for the word "Add"
- [x] The colour of the button does not seem to be the right one. See the UI Kit for the right code for the green (Link below)
- [x] "Add to query" button should be disabled by default when no set is selected

### Resources
https://www.notion.so/ferlab/Using-a-set-in-the-Cohort-Builder-848a37fb6cdc406297012aed10be4bde

https://www.figma.com/file/MKWJJXL7sz4poiIv5bKNtz/KF-UI-Kit-ant.design-v4-update?node-id=0%3A2368

**Comment by denis-crsj** [comment]
@evans-g-crsj 3 petits defects ont été ajoutés à la description plus haut. Je remet donc la carte dans "In progress"

**Comment by denis-crsj** [comment]
All defects have been fixed, ready to release.
