### ISSUE TITLE
Real determination of access should be by reading the acl at the file level

### ISSUE THREAD

**Issue by denis-crsj** [kids-first/kf-portal-ui#2672]
While a sample can have a consent code, the ACL that matters in the end is at the file level. The real determination of access should be by reading the ACL at the file level.

### Sub-Tasks
We'll consider that there is always 2 ACLs maximum for the files (1 for the Admin and 1 for the consent code).
- [x] The ETL needs to take into consideration only the one associated to the consent code. In this example: cd659215-e25c-4d2d-b4f9-117f708b6059 -> [SD_BHJXBDQK, SD_BHJXBDQK.c1], the "SD_BHJXBDQK" has to be ignored.
- [x] Based on a file S3 URL, we need to be able to retrieve it's ACLs in the Data Service (genomic_files table)
- [x] If files have the "*" ACL (Open Access), everyone can see them.
- [x] If a user has access to the consent code that is the same as the study ID or a consent code finishing by .c999, they need to have access to every files of the study.
- [ ] Ignoring files with multiple consent codes in their ACLs for now. Example, if a file has .c1 and .c2 consent codes, we will ignore it.

**Comment by denis-crsj** [comment]
Last item on the list has been transferred to it's own separate issue : https://github.com/kids-first/kf-portal-ui/issues/2677
