### ISSUE TITLE
Variant index phase 1

### ISSUE THREAD

**Issue by botekchristophe** [kids-first/kf-portal-ui#2881]
### Feature

as a web dev, I can build a Variant Search Web interface 

### Acceptance Criteria

**Scenario:** Web devs can connect to a Elastic search to fetch variant data

### Sub-Tasks

- [ ] publish the variant data as json on s3
- [ ] deploy an elastic search cluster
- [ ] publish the variant data in elasticsearch based on the data in s3
