### ISSUE TITLE
Variant Workbench : Add inheritence to orphanet gene set

### ISSUE THREAD

**Issue by jecos** [kids-first/kf-portal-ui#2927]
### Feature

In `orphanet_gene_set` tables, we need an new column that gives the `inheritence`. For now, source of `orphanet_gene_set` table is this xml file :
[http://www.orphadata.org/data/xml/en_product6.xml](http://www.orphadata.org/data/xml/en_product6.xml)

Inheritence information is given by another file : 
[http://www.orphadata.org/data/xml/en_product9_ages.xml](http://www.orphadata.org/data/xml/en_product9_ages.xml)

We should load the 2 files and join these together. 

### Sub-Tasks
- [ ] Automcatically load the 2 files
- [ ] Join it together
- [ ] Documentation in notion and in tables column. Description of tables can be found in this PDF : http://www.orphadata.org/cgi-bin/img/PDF/OrphadataFreeAccessProductsDescription.pdf
