### ISSUE TITLE
[Epic] Studies Page fixes for V1

### ISSUE THREAD

**Issue by vferretti** [kids-first/kf-portal-ui#3104]
- [ ] Add the text search bar at the top of the facets panel. Support search by study codes and study names #3014
- [ ] add Showing 1 - 10 of 28 above the table #3130
- [ ] Facets panel: implement styling as defined by Lucas in the spec #3131 
- [ ] Add tooltips on the data category column titles. Use the names showed in the facet Data Categories. SV is Structural Variation #3125
- [ ] Replace facet name Data Categories by Data Category #3132
- [ ] Make sure that facet names are the same as the ones displayed in the query bar. Currently, the facet Domain is in lower case in the query i.e. domain = Cancer #3131 
- [ ] Experimental strategy = No Data instead of __missing__ in the query bar #3135 
- [ ] ~~Use short name instead of name from dataservice~~ (Moved to #3108)
- [ ] ~~Change the way family data is set : if there is family count = 0, then family data should be true. Otherwise, it should be false~~ (Moved to #3108)

**Comment by francisl** [comment]
Closing, please see subtasks
