### ISSUE TITLE
Per-Study ETL 

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#476]
We want to have an prod elastic search composed of many aliases study indices.

This will allow us to:
- run es on a single, or set, of studies and only update those
- update certain studies only as needed

To complete this epic, we need to make sure that we can: 
- [x] Run ETL on distinct studies/sets of studies
- [x] Respond to input from release coordinator task service 
- [x] Have portal respond correctly to multi-aliases index
- [x] Deploy task service to all three layers (dev/qa/prod)
- [x] Update Task Service with lastest ETL changes/variables
- [x] Add reference data to RDS (like HPO)
- [x] Add EMR
- [x] Publish ETL jar to S3 (jenkins)
- [x] Task service to track key-value pair to track release as a mapping. Each r3equest will look up the status of this.

**Comment by rosibaj** [comment]
Running on prod!!!
