### ISSUE TITLE
User tags Updates

### ISSUE THREAD

**Issue by rosibaj** [kids-first/kf-portal-ui#800]
Some duplicate user tags can be observed: 

![Screen Shot 2018-09-25 at 2.28.52 PM.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/853474d1-6d2e-41ff-8309-3c8d6850f2df)

**Expected Behaviour** A user should be able to type whatever they want (Pediatric cancer or Pediatric Cancer) and if it matches, it should be read as one tag.  

We need a back-end serialization to enforce non-duplicate tags, regardless of casing input on the UI. This should: 
- keep it all as lowercase in mongo
- change the visual rendering in the UI to capitalize it on suggested items
- allow users to input capitol letters

**Todos**
- [x] ensure the user schema fed to mongodb specifies lowercase for the `interests` field (https://mongoosejs.com/docs/schematypes.html). This should be done in `kf-persona`.
- [ ] migrate existing data to lowercase all the `interests` field values
- [x] remove serialization in the UI to allow for typing capital letters
- [x] update UI to "recapitalize" the values with css `text-transform: capitalize`

**Comment by ciaranschutte** [comment]
@rosibaj  https://5bae2773b13fb14277dbb4f8--kf-qa-portal.netlify.com/
UI part of this is complete

**Comment by rosibaj** [comment]
@ciaranschutte A couple things
- [ ]  I can still add a "duplicate" with a capital letter.  I see Iguanas as a new interest (or hello this is a test) with different casing.  However, when i click on the "new interest" that is working correctly (no duplicate added) It seems weird for this to be listed as a "new interest"; can it just be a suggestion?
<img width="431" alt="screen shot 2018-10-05 at 3 55 24 pm" src="https://user-images.githubusercontent.com/15824252/46557216-2af3ef00-c8b7-11e8-9591-95896dfd67b7.png">

<img width="461" alt="screen shot 2018-10-05 at 3 57 02 pm" src="https://user-images.githubusercontent.com/15824252/46557281-5545ac80-c8b7-11e8-81f6-66aadb668e21.png">
- [ ]  I think this is part of the same thing, but the suggestions should follow the same casing as the interests
<img width="433" alt="screen shot 2018-10-05 at 4 01 34 pm" src="https://user-images.githubusercontent.com/15824252/46557531-309e0480-c8b8-11e8-9261-396de1e297fc.png">

**Comment by ciaranschutte** [comment]
Updated migration
Split schema change and migration into two PRs

**Comment by ciaranschutte** [comment]
@rosibaj just fixing these points.
Does it even make sense to have 'iguanas' as a suggestion if it's already selected as an interest?

**Comment by rosibaj** [comment]
@ciaranschutte good point!  It should not show already selected interests as suggestions

**Comment by ciaranschutte** [comment]
@rosibaj  https://5bbea0094ed62f792faa2fe6--kf-qa-portal.netlify.com/
New fixes added
